### ISSUE TITLE
net/ipx.h error after installing latest linux headers

### ISSUE THREAD

**Issue by Its-Choudhary** [davidbombal/Kali-Linux#5]
after installing latest linux headers [linux-headers-5.14.0-kali6-amd64   ] is stopped installing because linux stopped the support on net/ipx.h

please help ASAP

![Screenshot_2022-01-07_00_45_55](https://user-images.githubusercontent.com/89649372/148438901-386cc480-1c79-4a66-95b3-ebd432d0b5ba.png)

**Comment by 0hv1** [comment]
use this commands:
1.> sudo apt-get install libnl-3-dev
2.> sudo apt-get install libnl-genl-3-dev
3.> sudo apt-get install libssl

**Comment by Its-Choudhary** [comment]
> sudo apt-get install libssl

nope it didn't work. same problem occurring.after bit of research i find out that after kernel update to 5.15.1-amd64-desktop they dropped the support

**Comment by Micoder-dev** [comment]
Same problem here.... 
![Uploading IMG_20220110_110143.jpg…]()

**Comment by Its-Choudhary** [comment]
i have a solution we can try if you are using old kali linux, means you can still have the ipx file in the old kernel folder, just copy the ipx.h files form there and put in the new kernel folder for ex--

/usr/src/linux-5.8.11/include/uapi/linux/ipx.h
/usr/src/linux-5.8.11/include/net/ipx.h

to

/usr/src/linux-5.15.5/include/uapi/linux/ipx.h
/usr/src/linux-5.15.5/include/net/ipx.h

if you have any kernel before 5.15.0 then do this method and if you have extra time upload the ipx.h file here so others can install.

**Comment by harkaran911** [comment]
> i have a solution we can try if you are using old kali linux, means you can still have the ipx file in the old kernel folder, just copy the ipx.h files form there and put in the new kernel folder for ex--
> 
> /usr/src/linux-5.8.11/include/uapi/linux/ipx.h /usr/src/linux-5.8.11/include/net/ipx.h
> 
> to
> 
> /usr/src/linux-5.15.5/include/uapi/linux/ipx.h /usr/src/linux-5.15.5/include/net/ipx.h
> 
> if you have any kernel before 5.15.0 then do this method and if you have extra time upload the ipx.h file here so others can install.

Hey can you exactly tell me which version supports the ipx so that I install that? Currently I am using 5.15.0-kali2-amd64. Please reply.

**Comment by harkaran911** [comment]
> i have a solution we can try if you are using old kali linux, means you can still have the ipx file in the old kernel folder, just copy the ipx.h files form there and put in the new kernel folder for ex--
> 
> /usr/src/linux-5.8.11/include/uapi/linux/ipx.h /usr/src/linux-5.8.11/include/net/ipx.h
> 
> to
> 
> /usr/src/linux-5.15.5/include/uapi/linux/ipx.h /usr/src/linux-5.15.5/include/net/ipx.h
> 
> if you have any kernel before 5.15.0 then do this method and if you have extra time upload the ipx.h file here so others can install.

Please reply counting on you.

**Comment by Its-Choudhary** [comment]
> 

sorry for late reply
use version before 5.15.0 like you can find the ipx.h file in 5.14 or 5.13 etc. 
i can't try the above method i mentioned because i installed the linux fresh a few weeks so i don't have previous kernels version.

**Comment by Micoder-dev** [comment]
> > i have a solution we can try if you are using old kali linux, means you can still have the ipx file in the old kernel folder, just copy the ipx.h files form there and put in the new kernel folder for ex--
> > /usr/src/linux-5.8.11/include/uapi/linux/ipx.h /usr/src/linux-5.8.11/include/net/ipx.h
> > to
> > /usr/src/linux-5.15.5/include/uapi/linux/ipx.h /usr/src/linux-5.15.5/include/net/ipx.h
> > if you have any kernel before 5.15.0 then do this method and if you have extra time upload the ipx.h file here so others can install.
> 
> Please reply counting on you.

You can use this driver for latest kalilinux https://github.com/drygdryg/rtl8188eus/commit/4830d3906230a4d80ba67709a06c9d5b99764839

**Comment by Its-Choudhary** [comment]
> > > i have a solution we can try if you are using old kali linux, means you can still have the ipx file in the old kernel folder, just copy the ipx.h files form there and put in the new kernel folder for ex--
> > > /usr/src/linux-5.8.11/include/uapi/linux/ipx.h /usr/src/linux-5.8.11/include/net/ipx.h
> > > to
> > > /usr/src/linux-5.15.5/include/uapi/linux/ipx.h /usr/src/linux-5.15.5/include/net/ipx.h
> > > if you have any kernel before 5.15.0 then do this method and if you have extra time upload the ipx.h file here so others can install.
> > 
> > 
> > Please reply counting on you.
> 
> You can use this driver for latest kalilinux [drygdryg/rtl8188eus@4830d39](https://github.com/drygdryg/rtl8188eus/commit/4830d3906230a4d80ba67709a06c9d5b99764839)

yes it worked. IDK i used it before but it didn't work, now today after updating all and once again i tried this and this time it worked. Thanks a lot man.

**Comment by Its-Choudhary** [comment]
> > i have a solution we can try if you are using old kali linux, means you can still have the ipx file in the old kernel folder, just copy the ipx.h files form there and put in the new kernel folder for ex--
> > /usr/src/linux-5.8.11/include/uapi/linux/ipx.h /usr/src/linux-5.8.11/include/net/ipx.h
> > to
> > /usr/src/linux-5.15.5/include/uapi/linux/ipx.h /usr/src/linux-5.15.5/include/net/ipx.h
> > if you have any kernel before 5.15.0 then do this method and if you have extra time upload the ipx.h file here so others can install.
> 
> Please reply counting on you.

https://github.com/drygdryg/rtl8188eus/commit/4830d3906230a4d80ba67709a06c9d5b99764839 
try this one and follow all the steps which are mentioned in David Cheat Sheet

**Comment by harkaran911** [comment]
> > > i have a solution we can try if you are using old kali linux, means you can still have the ipx file in the old kernel folder, just copy the ipx.h files form there and put in the new kernel folder for ex--
> > > /usr/src/linux-5.8.11/include/uapi/linux/ipx.h /usr/src/linux-5.8.11/include/net/ipx.h
> > > to
> > > /usr/src/linux-5.15.5/include/uapi/linux/ipx.h /usr/src/linux-5.15.5/include/net/ipx.h
> > > if you have any kernel before 5.15.0 then do this method and if you have extra time upload the ipx.h file here so others can install.
> > 
> > 
> > Please reply counting on you.
> 
> [drygdryg/rtl8188eus@4830d39](https://github.com/drygdryg/rtl8188eus/commit/4830d3906230a4d80ba67709a06c9d5b99764839) try this one and follow all the steps which are mentioned in David Cheat Sheet

For Anyone who cannot replace the ipx.h file from another lower version kernel.

I am posting both the ipx.h files.

uapi --> https://ufile.io/hssbioqf
net --> https://ufile.io/ltf82be9

Hope it helps you.

**Comment by Moalmasry1811** [comment]
> > > > i have a solution we can try if you are using old kali linux, means you can still have the ipx file in the old kernel folder, just copy the ipx.h files form there and put in the new kernel folder for ex--
> > > > /usr/src/linux-5.8.11/include/uapi/linux/ipx.h /usr/src/linux-5.8.11/include/net/ipx.h
> > > > to
> > > > /usr/src/linux-5.15.5/include/uapi/linux/ipx.h /usr/src/linux-5.15.5/include/net/ipx.h
> > > > if you have any kernel before 5.15.0 then do this method and if you have extra time upload the ipx.h file here so others can install.
> > > 
> > > 
> > > Please reply counting on you.
> > 
> > 
> > [drygdryg/rtl8188eus@4830d39](https://github.com/drygdryg/rtl8188eus/commit/4830d3906230a4d80ba67709a06c9d5b99764839) try this one and follow all the steps which are mentioned in David Cheat Sheet
> 
> For Anyone who cannot replace the ipx.h file from another lower version kernel.
> 
> I am posting both the ipx.h files.
> 
> uapi --> https://ufile.io/hssbioqf net --> https://ufile.io/ltf82be9
> 
> Hope it helps you.

can u plz upload these 2 files again ?

**Comment by harkaran911** [comment]
> > > > > i have a solution we can try if you are using old kali linux, means you can still have the ipx file in the old kernel folder, just copy the ipx.h files form there and put in the new kernel folder for ex--
> > > > > /usr/src/linux-5.8.11/include/uapi/linux/ipx.h /usr/src/linux-5.8.11/include/net/ipx.h
> > > > > to
> > > > > /usr/src/linux-5.15.5/include/uapi/linux/ipx.h /usr/src/linux-5.15.5/include/net/ipx.h
> > > > > if you have any kernel before 5.15.0 then do this method and if you have extra time upload the ipx.h file here so others can install.
> > > > 
> > > > 
> > > > Please reply counting on you.
> > > 
> > > 
> > > [drygdryg/rtl8188eus@4830d39](https://github.com/drygdryg/rtl8188eus/commit/4830d3906230a4d80ba67709a06c9d5b99764839) try this one and follow all the steps which are mentioned in David Cheat Sheet
> > 
> > 
> > For Anyone who cannot replace the ipx.h file from another lower version kernel.
> > I am posting both the ipx.h files.
> > uapi --> https://ufile.io/hssbioqf net --> https://ufile.io/ltf82be9
> > Hope it helps you.
> 
> can u plz upload these 2 files again ?

Can you wait till tomorrow. I know that the links have expired I will create new links and upload it here.

Please wait till tomorrow.

**Comment by harkaran911** [comment]
> 

Ok i have made links. 

net --> https://ufile.io/dfuk9yxi
uapi --> https://ufile.io/w5d4tof1

Sorry for the inconvenience.
