### ISSUE TITLE
"r8188eu.ko" rmmod: ERROR: Module r8188eu is not currently loaded

### ISSUE THREAD

**Issue by senpa1-13** [davidbombal/Kali-Linux#8]
I know there is a thread about this, but the issue is not resolved in my case. I have used both the commands but it is showing me errors, 
modprobe: FATAL: Module r8188eu.ko not found in directory /lib/modules/5.15.0-kali3-amd64
rmmod: ERROR: Module r8188eu is not currently loaded
Please help me out, also I upgraded my Kali Linux too

**Comment by elon-fask** [comment]
here the solution 
https://github.com/Elon-Fask/Kali-Linux

**Comment by PetrosPRO** [comment]
> 

I've done everything step by step , but it crashes . Doesnt let me to run the "rm" command and when i run "make" it gets 2 errors . Please help !

**Comment by ghost** [comment]
pudiste encontrar una solucion?

**Comment by Professionalus** [comment]
@Elon-Fask 
You missed the "-i" after dpkg to install the header.

**Comment by linuxqueenn12** [comment]
can anyone to help me in the TP-link 
Error for wireless request "Set Mode" (8B06) :
    SET failed on device wlan0 ; Invalid argument.
